hpc_mpi_helloworld_with3roundtrips: hpc_mpi_helloworld_with3roundtrips.c
	mpicc -o hpc_mpi_helloworld_with3roundtrips hpc_mpi_helloworld_with3roundtrips.c

clean:
	/bin/rm -f hpc_mpi_helloworld_with3roundtrips *.o
